sudo: required
services:
  - docker
before_install:
  - docker build -t koyedeji/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true koyedeji/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-352522536367"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"